databases:
  - name: latamgateway-challenge
    databaseName: latamgateway
    user: latamgateway
    plan: free

services:
  - type: web
    name: latamgateway-challenge
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: latamgateway-challenge
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default